### ISSUE TITLE
Live hero breakpoint issue

### ISSUE THREAD

**Issue by jonitrythall** [elaconf/elaconf.github.io#118]
There is an issue with the hero breaking between the `1000px` and `1180px` breakpoint:

<img width="1087" alt="screen shot 2017-06-09 at 8 54 02 pm" src="https://user-images.githubusercontent.com/5723303/26998703-e3db7ddc-4d55-11e7-95a7-6437f4fec953.png">

The icons also become too close together here. 

This only exists on the live site and I can't reproduce the issue locally. 

I also noticed that the font and logo size and spacing is visually different between localhost and live?

**localhost:** 

<img width="1209" alt="screen shot 2017-06-09 at 8 55 59 pm" src="https://user-images.githubusercontent.com/5723303/26998715-17dd88aa-4d56-11e7-9aaf-9a6626815be0.png">

**live:** 

<img width="1209" alt="screen shot 2017-06-09 at 8 56 44 pm" src="https://user-images.githubusercontent.com/5723303/26998721-2cbd8f86-4d56-11e7-804b-f0df851fd294.png">

**Comment by katydecorah** [comment]
> I also noticed that the font and logo size and spacing is visually different between localhost and live?

@jonitrythall I'm unable to reproduce. Perhaps this is due to changes you made in
https://github.com/elaconf/elaconf.github.io/commit/f0b151455748982effc183f7258448d0791a83c9 that weren't pushed to production yet?
