### ISSUE TITLE
Add "Individuals" tier to sponsorship levels

### ISSUE THREAD

**Issue by jonitrythall** [elaconf/elaconf.github.io#78]
In anticipation of pending co-working space contributions

**Comment by jonitrythall** [comment]
Not sure they will want this as they are creating a new community logo for their contribution. 

Also haven't heard from DDG so thinking this issue should be **on hold**.

**Comment by katydecorah** [comment]
Sounds good! Thinking we can list names and link to something they'd like (website/twitter/etc). Something like:

![image](https://cloud.githubusercontent.com/assets/2180540/19653971/985e4120-99e4-11e6-9de1-bc9649953ff4.png)

**Comment by jonitrythall** [comment]
This is perfect!
 
I also got a couple names from the DDG folks to add: Jag Talon, Gabriel Weinberg
